apiVersion: batch/v1
kind: Job
metadata:
  name: clrguesgm-job
spec:
  template:
    spec:
      containers:
      - name: clrguesgm-job
        image: yash5090/clrguesgm:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
